# Generated by Django 3.2.8 on 2023-09-06 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectlist_app', '0004_auto_20230905_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comentario_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
