# Generated by Django 3.2.8 on 2023-09-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectlist_app', '0005_comment_comentario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
